CREATE TABLE IF NOT EXISTS sync_task_lock
(
    id             INT AUTO_INCREMENT PRIMARY KEY COMMENT '自增主键',
    lock_id        INT      NOT NULL UNIQUE COMMENT '锁ID',
    created_stime  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    modified_stime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COMMENT = '表数据同步任务锁';